# Generated by Django 3.2.4 on 2021-07-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_comment_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_like',
            field=models.IntegerField(default=0, null=True, verbose_name='Beğeni'),
        ),
    ]
