# Generated by Django 3.2.4 on 2021-07-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_comment_comment_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['comment_like']},
        ),
    ]
